name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge test -vvv
      - run: forge snapshot

  formal-verfication:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        ruleset:
          - "listing.conf"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          forge build
      - run: |
          pip3 install -r requirements.txt
      - run: |
          msg="${2:-"$(hostname) - ${conf_file} - $(date +%s)"}"

          pip3 install solc-select
          solc-select install ${SOLC_VERSION}

          certoraRun "./certora/confs/${{ matrix.ruleset }}" \
            --msg "$(hostname) - ${{ matrix.ruleset }} - $(date +%s)" \
            --wait_for_results all \
            --rule_sanity basic
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
          SOLC_VERSION: 0.8.20
