name: "[sepolia-deploy] deploy listing"
on:
  workflow_dispatch:
    inputs:
      tokenMintSupply:
        description: "Maximum token supply minted"
        required: true
      mintAddress:
        description: "Mint Address"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: sepolia
      url: https://term-finance.github.io/term-finance-listing/
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
      - run: yarn install --immutable
      - uses: foundry-rs/foundry-toolchain@v1
      - run: yarn install
      - run: forge install
      - run: forge build
      - run: forge tree
      - run: forge script script/RepoTokenLinkedList.s.sol:DeployRepoTokenLinkedList --rpc-url $RPC_URL --broadcast --verify --verbosity 4
        env:
          RPC_URL:  ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          CONTROLLER_ADDRESS: ${{ vars.CONTROLLER_ADDRESS }}
          DISCOUNT_RATE_ADAPTER_ADDRESS: ${{ vars.DISCOUNT_RATE_ADAPTER_ADDRESS }}
          ADMIN_ADDRESS: ${{ vars.ADMIN_ADDRESS }}
          DEVOPS_ADDRESS: ${{ vars.DEVOPS_ADDRESS }}
  